abstract: Plugin to use ModBlosxom for Egg.
author: Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>
build_requires: 
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Egg-Plugin-Blosxom
no_index: 
  directory: 
    - inc
    - t
requires: 
  Egg::Release: 1.2001
  HTTP::Request::Common: 0
  Jcode: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  List::Uniq: 0.1
  Text::Hatena: 0.2
  Text::Tags: 0.04
version: 0.01
